name: build

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Build solution
        run: npm run build
        env:
          CI: true